// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(RPSDbContext))]
    partial class RPSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Level", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("LevelItems");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Beginner"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Intermediate"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Advanced"
                        });
                });

            modelBuilder.Entity("Match", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AIChoice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerChoice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("LevelID");

                    b.HasIndex("UserID");

                    b.ToTable("MatchItems");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("UserStats", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Draws")
                        .HasColumnType("REAL");

                    b.Property<int>("LeveLID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Losses")
                        .HasColumnType("REAL");

                    b.Property<string>("Nemesis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesPaperUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesRockUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesScissorsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Wins")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("LeveLID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("UserStatsItems");
                });

            modelBuilder.Entity("Match", b =>
                {
                    b.HasOne("Level", "Level")
                        .WithMany("Matches")
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("Matches")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserStats", b =>
                {
                    b.HasOne("Level", "Level")
                        .WithMany("UserStats")
                        .HasForeignKey("LeveLID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithOne("UserStats")
                        .HasForeignKey("UserStats", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Level", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("UserStats");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("UserStats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
